version: '3.9'

services:
  CodeProjectAI:
    image: codeproject/ai-server:cuda11_7
    container_name: "codeproject-ai-server-cuda"
    restart: unless-stopped
    ports:
      - "32168:32168/tcp"
      - "32168:32168/udp"
    environment:
      - TZ=America/Toronto
    volumes:
      - codeproject_ai_data_cuda11_7:/etc/codeproject/ai
      - codeproject_ai_modules_cuda11_7:/app/modules
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
volumes:
  codeproject_ai_data_cuda11_7:
  codeproject_ai_modules_cuda11_7:
